baseURL: "https://gameokko.com/"
title: GAME OKKO
paginate: 50
theme: PaperMod

pluralizeListTitles : false

defaultContentLanguage: en
defaultContentLanguageInSubdir: false
languages:
  en:
    contentDir: content/en
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    name: English
    title: English
    homeInfoParams:
      Title: "News & Game Wikis"
      Content: Tra cứu thông tin về trò chơi yêu thích
    ## socialIcons:
    ##- name: youtube
    ##  url: "https://youtube.com/"
    ##- name: facebook
    ##  url: "https://facebook.com/" 
    ##- name: buymeacoffee
    ##  url: "https://www.buymeacoffee.com/"
    ##- name: kofi
    ##  url: "https://ko-fi.com/"  
 
    params:
      subtitle: News, Game Wiki, Game Guide
    title: GAME OKKO
    weight: 1 
    menu:
    menu:
      main: 
      - name: Onmyoji
        pageRef: /onmyoji/
        weight: 20 
  vi:
    contentDir: content/vi
    disabled: false
    languageCode: vi
    languageDirection: ltr
    languageName: Tiếng Việt  
    homeInfoParams:
      Title: "News & Game Wikis"
      Content: Tra cứu thông tin về trò chơi yêu thích

    params:
      subtitle:  Game Wiki, Game Guide
    title: GAME OKKO
    menu:
      main: 
      - name: Onmyoji
        pageRef: /onmyoji/
        weight: 20 
    weight: 2

params:
  mainSections: 
  - onmyoji 
  - faqs 
  - news 
  - game-moi 

  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: GAME OKKO 
  description: "News & Game Wiki"
  keywords: [News, Game Wiki, Game Guide]
  author: okko
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]

  dateFormatEn: "January 2, 2006"
  dateFormatVi: "2/1/2006"
  defaultTheme: dark # auto , light
  disableThemeToggle: false

  hideAuthor: false
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: true
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/icon/favicon.ico"
    favicon16x16: "/icon/favicon-16x16.png"
    favicon32x32: "/icon/favicon-32x32.png"
    apple_touch_icon: "/icon/apple-touch-icon.png"
    safari_pinned_tab: "/icon/android-chrome-512x512.png"

  label:
    text: "GAME OKKO"
    icon: /icon/apple-touch-icon.png
    iconHeight: 35

