baseURL = "https://gameokko.com/"
title = "GAME OKKO"
paginate = 50
theme = "PaperMod"
pluralizeListTitles = false
defaultContentLanguage = "vi"
defaultContentLanguageInSubdir = true
 
[languages.en]
contentDir = "content/en"
disabled = false
languageCode = "en-US"
languageDirection = "ltr"
languageName = "English"
title = "GAME OKKO"
weight = 2

  [languages.en.params]
  name = "GAME OKKO"
  subtitle = "News, Game Wiki, Game Guide"



    [languages.en.params.homeInfoParams]
    Title = "News & Game Wikis"
    Content = "Look up information about your favorite game"

    [[languages.en.menu.main]]
    name = "Search"
    pageRef = "/search"
    weight = 10

    [[languages.en.menu.main]]
    name = "Onmyoji"
    pageRef = "/onmyoji/"
    weight = 20

    [[languages.en.menu.main]]
    name = "Sword Chronicles: Awaken"
    pageRef = "/sword-chronicles-awaken/"
    weight = 30



[languages.vi]
contentDir = "content/vi"
disabled = false
languageCode = "vi"
languageDirection = "ltr"
languageName = "Tiếng Việt"
title = "GAME OKKO"
weight = 1
 
  [languages.vi.params]
  subtitle = "Game Wiki, Game Guide"

    [languages.vi.params.homeInfoParams]
    Title = "News & Game Wikis"
    Content = "Tra cứu thông tin về trò chơi yêu thích"
    
    [[languages.vi.menu.main]]
    name = "Tìm kiếm"
    pageRef = "/search"
    weight = 10

    [[languages.vi.menu.main]]
    name = "Onmyoji"
    pageRef = "/onmyoji/"
    weight = 20

    [[languages.vi.menu.main]]
    name = "Sword Chronicles: Awaken"
    pageRef = "/sword-chronicles-awaken/"
    weight = 30


 

[params]
mainSections = [ "sword-chronicles-awaken", "onmyoji"]
env = "production"
title = "GAME OKKO"
description = "News & Game Wiki"
keywords = [ "News", "Game Wiki", "Game Guide" ]
author = "okko"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
dateFormatEn = "January 2, 2006"
dateFormatVi = "2/1/2006"
defaultTheme = "dark"
disableThemeToggle = true
hideAuthor = false
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = false
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = true
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false 



  [params.assets]
  favicon = "/icon/favicon.ico"
  favicon16x16 = "/icon/favicon-16x16.png"
  favicon32x32 = "/icon/favicon-32x32.png"
  apple_touch_icon = "/icon/apple-touch-icon.png"
  safari_pinned_tab = "/icon/android-chrome-512x512.png"

  [params.label]
  text = "GAME OKKO"
  icon = "/icon/apple-touch-icon.png"
  iconHeight = 35

[outputs]
home = [ "HTML", "RSS", "JSON" ]
